
  version: '3.8'

  services:
    postgres:
      image: postgres:15
      container_name: postgres-training-prod
      environment:
        POSTGRES_DB: ${POSTGRES_DB:-training}
        POSTGRES_USER: ${POSTGRES_USER:-student}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-securepass123}
      ports:
        - "${POSTGRES_PORT:-5432}:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./init-scripts:/docker-entrypoint-initdb.d
      networks:
        - training-network
      restart: unless-stopped
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-student} -d ${POSTGRES_DB:-training}"]
        interval: 30s
        timeout: 10s
        retries: 3

    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin-training
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@training.com}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      ports:
        - "${PGADMIN_PORT:-8080}:80"
      volumes:
        - pgadmin_data:/var/lib/pgadmin
      networks:
        - training-network
      depends_on:
        postgres:
          condition: service_healthy
      restart: unless-stopped

  networks:
    training-network:
      driver: bridge

  volumes:
    postgres_data:
    pgadmin_data: